import 'dart:ui' hide FragmentShader;

import 'package:flame_3d/graphics.dart';
import 'package:flame_3d/resources.dart';

abstract interface class VoxelMaterialControls {
  void setFogRange(double start, double end);
  void setRenderStyle({
    required int debugView,
    required double fogDensity,
    required bool ambientOcclusion,
  });
}

/// Atlas material that preserves per-vertex baked lighting/AO.
final class VoxelMaterial extends Material implements VoxelMaterialControls {
  VoxelMaterial({
    this.albedoColor = const Color(0xFFFFFFFF),
    this.fogStart = 96,
    this.fogEnd = 160,
    Texture? albedoTexture,
  }) : albedoTexture = albedoTexture ?? Texture.standard,
       super(
         vertexShader: VertexShader.fromAsset(
           'assets/shaders/voxel_material.shaderbundle',
           slots: ['VertexInfo', 'JointMatrices'],
         ),
         fragmentShader: FragmentShader.fromAsset(
           'assets/shaders/voxel_material.shaderbundle',
           slots: ['albedoTexture', 'Material', 'Camera'],
         ),
       );

  Color albedoColor;
  Color fogColor = const Color(0xFF82C8FF);
  Texture albedoTexture;

  /// World-space fog range. The fragment shader uses the Classic sky color.
  double fogStart;
  double fogEnd;
  double fogDensity = 1;
  double bakedLightStrength = 1;
  int debugView = 0;

  @override
  void setFogRange(double start, double end) {
    fogStart = start;
    fogEnd = end;
  }

  @override
  void setRenderStyle({
    required int debugView,
    required double fogDensity,
    required bool ambientOcclusion,
  }) {
    this.debugView = debugView.clamp(0, 6);
    this.fogDensity = fogDensity.clamp(0, 1);
    bakedLightStrength = ambientOcclusion ? 1 : 0;
  }

  @override
  void apply(covariant RenderContext3D context) {
    vertexShader
      ..setMatrix4('VertexInfo.model', context.model)
      ..setMatrix4('VertexInfo.view', context.view)
      ..setMatrix4('VertexInfo.projection', context.projection);
    fragmentShader
      ..setTexture('albedoTexture', albedoTexture)
      ..setColor('Material.albedoColor', albedoColor)
      ..setColor('Material.fogColor', fogColor)
      ..setFloat('Material.fogStart', fogStart)
      ..setFloat('Material.fogEnd', fogEnd)
      ..setFloat('Material.fogDensity', fogDensity)
      ..setFloat('Material.bakedLightStrength', bakedLightStrength)
      ..setFloat('Material.debugView', debugView.toDouble())
      ..setFloat('Material.brightness', 1)
      ..setVector3('Camera.position', context.cameraPosition);
  }
}

/// WebGPU fallback with baked vertex lighting and a hard alpha cutout.
///
/// The bundle is generated by `bin/build_web_voxel_shader.dart` from
/// flame_3d's bundled unlit vertex shader/reflection, so it does not require
/// the external naga CLI.
final class WebVoxelMaterial extends Material implements VoxelMaterialControls {
  WebVoxelMaterial({
    this.albedoColor = const Color(0xFFFFFFFF),
    Texture? albedoTexture,
  }) : albedoTexture = albedoTexture ?? Texture.standard,
       super(
         vertexShader: VertexShader.fromAsset(
           'assets/shaders/web_voxel_material.shaderbundle',
           slots: ['VertexInfo', 'JointMatrices'],
         ),
         fragmentShader: FragmentShader.fromAsset(
           'assets/shaders/web_voxel_material.shaderbundle',
           slots: ['albedoTexture', 'Material', 'Camera'],
         ),
       );

  Color albedoColor;
  Texture albedoTexture;
  Color fogColor = const Color(0xFF82C8FF);
  double fogStart = 96;
  double fogEnd = 160;
  double fogDensity = 1;
  double bakedLightStrength = 1;
  int debugView = 0;

  @override
  void setFogRange(double start, double end) {
    fogStart = start;
    fogEnd = end;
  }

  @override
  void setRenderStyle({
    required int debugView,
    required double fogDensity,
    required bool ambientOcclusion,
  }) {
    this.debugView = debugView.clamp(0, 6);
    this.fogDensity = fogDensity.clamp(0, 1);
    bakedLightStrength = ambientOcclusion ? 1 : 0;
  }

  @override
  void apply(covariant RenderContext3D context) {
    vertexShader
      ..setMatrix4('VertexInfo.model', context.model)
      ..setMatrix4('VertexInfo.view', context.view)
      ..setMatrix4('VertexInfo.projection', context.projection);
    fragmentShader
      ..setTexture('albedoTexture', albedoTexture)
      ..setColor('Material.albedoColor', albedoColor)
      ..setColor('Material.fogColor', fogColor)
      ..setFloat('Material.fogStart', fogStart)
      ..setFloat('Material.fogEnd', fogEnd)
      ..setFloat('Material.fogDensity', fogDensity)
      ..setFloat('Material.bakedLightStrength', bakedLightStrength)
      ..setFloat('Material.debugView', debugView.toDouble())
      ..setFloat('Material.brightness', 1)
      ..setVector3('Camera.position', context.cameraPosition);
  }
}
